# -*- coding: utf-8 -*-
"""FaceAttendance_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wDEjwmrBX81xTfSjH_9K77ZWZ-HnojfH
"""

!git config --global user.email "wwwomkardey100@gmail.com"
!git config --global user.name "Omkar Dey"

from google.colab import drive
drive.mount('/content/drive')

import shutil
shutil.copy("/content/drive/MyDrive/Colab Notebooks/FaceAttendance_final.ipynb", "/content/CLASS-ATTENDANCE/")

# Commented out IPython magic to ensure Python compatibility.
# %cd /content
!git -C CLASS-ATTENDANCE add FaceAttendance_final.ipynb
!git -C CLASS-ATTENDANCE commit -m "Add face attendance notebook"
!git -C CLASS-ATTENDANCE push origin main

# Install required libraries
!pip install face_recognition
!pip install opencv-contrib-python
!pip install openpyxl

from google.colab import drive
drive.mount('/content/drive')

# Dataset Preparation (To generate frames from the given videos of the students)
import cv2
import face_recognition
import os

video_folder = "/content/drive/MyDrive/face_dataset"
dataset_path = "/content/drive/MyDrive/FaceAttendance/dataset"

os.makedirs(dataset_path, exist_ok=True)

videos = os.listdir(video_folder)

for video_file in videos:

    video_path = os.path.join(video_folder, video_file)

    name = os.path.splitext(video_file)[0]
    name = name.title()
    folder_name = name.replace(" ", "_")

    student_folder = os.path.join(dataset_path, folder_name)
    os.makedirs(student_folder, exist_ok=True)

    # Skip if already processed
    if len(os.listdir(student_folder)) > 15:
        print(folder_name, "already done")
        continue

    cap = cv2.VideoCapture(video_path)

    frame_total = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    step = 15   # jump 15 frames at a time

    saved_count = 0

    for frame_number in range(0, frame_total, step):

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_number)
        ret, frame = cap.read()

        if not ret:
            break

        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        faces = face_recognition.face_locations(rgb, model="hog")

        for top, right, bottom, left in faces:

            face = frame[top:bottom, left:right]

            filename = os.path.join(
                student_folder,
                f"{folder_name}_{saved_count}.jpg"
            )

            cv2.imwrite(filename, face)
            saved_count += 1

    cap.release()

    print(folder_name, "→", saved_count, "faces saved")

# Generate face embeddings from dataset images

import face_recognition
import os
import pickle

dataset_path = "/content/drive/MyDrive/FaceAttendance/dataset"

known_embeddings = []
known_names = []

for person_name in os.listdir(dataset_path):

    person_folder = os.path.join(dataset_path, person_name)

    if not os.path.isdir(person_folder):
        continue

    print("Processing:", person_name)

    for image_name in os.listdir(person_folder):

        image_path = os.path.join(person_folder, image_name)

        image = face_recognition.load_image_file(image_path)

        encodings = face_recognition.face_encodings(image)

        if len(encodings) > 0:
            known_embeddings.append(encodings[0])
            known_names.append(person_name)


data = {
    "embeddings": known_embeddings,
    "names": known_names
}

with open("/content/drive/MyDrive/FaceAttendance/embedding_database.pkl", "wb") as f:
    pickle.dump(data, f)

print("Embedding database created successfully!")

# Create student database Excel — run once

import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment
import os

dataset_path  = "/content/drive/MyDrive/FaceAttendance/dataset"
excel_db_path = "/content/drive/MyDrive/FaceAttendance/student_database.xlsx"

student_names = sorted([
    d for d in os.listdir(dataset_path)
    if os.path.isdir(os.path.join(dataset_path, d))
])

print(f"Found {len(student_names)} students:")
for s in student_names:
    print(" ", s)

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "Students"

header_fill = PatternFill("solid", fgColor="1F4E79")
header_font = Font(bold=True, color="FFFFFF", size=12)

for col, h in enumerate(["S.No", "Student ID", "Name", "Folder Name"], 1):
    cell = ws.cell(row=1, column=col, value=h)
    cell.fill = header_fill
    cell.font = header_font
    cell.alignment = Alignment(horizontal="center")

for i, folder_name in enumerate(student_names, 1):
    display_name = folder_name.replace("_", " ").title()
    ws.append([i, f"STU{i:03d}", display_name, folder_name])

ws.column_dimensions['A'].width = 8
ws.column_dimensions['B'].width = 12
ws.column_dimensions['C'].width = 28
ws.column_dimensions['D'].width = 28

wb.save(excel_db_path)
print(f"\n✅ Student database saved → {excel_db_path}")

import face_recognition
import cv2
import pickle
import os
import numpy as np
import openpyxl
from openpyxl.styles import PatternFill, Font, Alignment
from datetime import datetime
from google.colab.patches import cv2_imshow

# Load embedding database
with open("/content/drive/MyDrive/FaceAttendance/embedding_database.pkl", "rb") as f:
    data = pickle.load(f)

known_embeddings = data["embeddings"]
known_names = data["names"]

image_folder = "/content/drive/MyDrive/testing_data"

present_students = set()

THRESHOLD = 0.5   # confidence threshold


for image_name in os.listdir(image_folder):

    image_path = os.path.join(image_folder, image_name)

    print("\nProcessing image:", image_name)

    image = cv2.imread(image_path)

    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Detect faces
    face_locations = face_recognition.face_locations(rgb_image, model="cnn")

    # Generate embeddings
    face_encodings = face_recognition.face_encodings(rgb_image, face_locations)

    print("Faces detected:", len(face_locations))


    for (top, right, bottom, left), encoding in zip(face_locations, face_encodings):

        # Compare with database
        face_distances = face_recognition.face_distance(known_embeddings, encoding)

        best_match_index = np.argmin(face_distances)

        distance = face_distances[best_match_index]

        if distance < THRESHOLD:
            name = known_names[best_match_index]
            present_students.add(name)
        else:
            name = "Unknown"

        print("Predicted:", name, "| Distance:", round(distance,3))


        # Draw bounding box
        cv2.rectangle(image, (left, top), (right, bottom), (0,255,0), 2)

        # Draw name
        cv2.putText(
            image,
            name,
            (left, top - 10),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.8,
            (0,255,0),
            2
        )

    # Show annotated image
    cv2_imshow(image)


print("\n========================")
print("Students Present:")
print("========================")

for student in sorted(present_students):
    print(student)


# ── Write attendance to Excel ─────────────────────────────────────────────────

excel_db_path    = "/content/drive/MyDrive/FaceAttendance/student_database.xlsx"
attendance_path  = "/content/drive/MyDrive/FaceAttendance/attendance.xlsx"

# Load master student list
db_wb = openpyxl.load_workbook(excel_db_path)
db_ws = db_wb["Students"]
all_students = {}
for row in db_ws.iter_rows(min_row=2, values_only=True):
    sno, sid, display, folder = row
    if folder:
        all_students[folder] = {"id": sid, "display": display}

# Load or create attendance workbook
if os.path.exists(attendance_path):
    att_wb = openpyxl.load_workbook(attendance_path)
else:
    att_wb = openpyxl.Workbook()
    if "Sheet" in att_wb.sheetnames:
        del att_wb["Sheet"]

# New sheet named by today's date
today_str  = datetime.now().strftime("%Y-%m-%d")
sheet_name = today_str
counter    = 1
while sheet_name in att_wb.sheetnames:
    sheet_name = f"{today_str}_run{counter}"
    counter   += 1

att_ws = att_wb.create_sheet(title=sheet_name)

hdr_fill     = PatternFill("solid", fgColor="1F4E79")
hdr_font     = Font(bold=True, color="FFFFFF", size=11)
present_fill = PatternFill("solid", fgColor="C6EFCE")
absent_fill  = PatternFill("solid", fgColor="FFC7CE")
center       = Alignment(horizontal="center")

for col, h in enumerate(["S.No", "Student ID", "Name", "Attendance"], 1):
    c = att_ws.cell(row=1, column=col, value=h)
    c.fill = hdr_fill; c.font = hdr_font; c.alignment = center

att_ws.column_dimensions['A'].width = 8
att_ws.column_dimensions['B'].width = 12
att_ws.column_dimensions['C'].width = 28
att_ws.column_dimensions['D'].width = 14

row_num = 2
present_count = 0
for folder_name, info in sorted(all_students.items()):
    is_present = folder_name in present_students
    status     = "Present" if is_present else "Absent"
    fill       = present_fill if is_present else absent_fill
    if is_present:
        present_count += 1
    att_ws.cell(row=row_num, column=1, value=row_num - 1).alignment = center
    att_ws.cell(row=row_num, column=2, value=info["id"]).alignment  = center
    att_ws.cell(row=row_num, column=3, value=info["display"])
    sc = att_ws.cell(row=row_num, column=4, value=status)
    sc.fill = fill; sc.alignment = center; sc.font = Font(bold=True)
    row_num += 1

att_ws.append([])
total = len(all_students)
att_ws.append([None, None, "Total Present",  present_count])
att_ws.append([None, None, "Total Absent",   total - present_count])
att_ws.append([None, None, "Total Students", total])

att_wb.save(attendance_path)

print("\n========================")
print("Attendance saved to Excel!")
print("========================")
print(f"Sheet: {sheet_name}")
print(f"Present: {present_count} / {total}")
print(f"Absent:  {total - present_count} / {total}")